### PR TITLE
Generate tags for all parts of the semantic version.

### LINKED ISSUE #3: Cannot reference action using @v1
To get this running in a workflow, I've had to specify an exact version: `university-of-york/aws-cfn-deploy-action@v1.0.3`

With `@v1`, I get the following error:

    Unable to resolve action university-of-york/aws-cfn-deploy-action@v1, unable to find version v1

### PR DESCRIPTION
**Pull request by rickselby**
This allows the action to be called with @v1.

This will close #3.

### CODE REVIEW

**Comment by rickselby** [comment]
If this is OK, I'll put in the same PR for `aws-sam-deploy-action`.

**Comment by choffee** [comment]
Seems reasonable.
Do we need to add the v? I've been adding v1.x and v1.1.x to the puppet repos but happy to go with plain version numbers.
 @danmilleruk

**Comment by rickselby** [comment]
Can we get this merged, if it's ok? I'd like to start migrating our repos from bitbucket, and would prefer to set up new workflows using @v1 rather than using @v1.1 and having to update every workflow when this action changes...

**Review by danmilleruk — APPROVED** [review]
This is reasonable. Happy to approve as it won't affect any existing versions.

**Pull request merged**
